import { CONTACTS, MEDIA, POPULAR_SERVICES } from './config.js';
import { getTariffs, syncOfficialSources } from './catalog.js';
import {
  addMessage, assignTicket, claimUpdate, cleanupUpdates, clearSession, closeTicket,
  createTicket, deliveryDone, deliveryFailed, enqueueDelivery, ensureV5Schema,
  getSession, getTicket, getTicketBySupportMessage, getUser, listQueue, listUserTickets,
  pendingDeliveries, releaseUpdate, saveProfile, sessionData, setLanguage, setRating,
  setSession, setStage, setSupportMessage, stats, upsertUser, updateTicketPhone
} from './v5-db.js';
import {
  accountingKeyboard, categoryMeta, classifyText, departmentsKeyboard, departmentMeta,
  homeKeyboard, L, languageKeyboard, normalizePhone, operatorKeyboard, operatorName,
  priorityFor, subscriberKeyboard, techKeyboard
} from './v5-ui.js';
import {
  answerCallback, contactKeyboard, copyMessage, editReplyMarkup, escapeHtml,
  inlineKeyboard, removeKeyboard, sendChatAction, sendMessage, sendPhoto
} from './telegram.js';

const VERSION='5.0.0';
const BOT_NAME='FiberNet Assistant';

function mainSupport(env,dept='tech'){
  return ({tech:env.TECH_CHAT_ID,accounting:env.ACCOUNTING_CHAT_ID,subscriber:env.SUBSCRIBER_CHAT_ID,connection:env.CONNECTION_CHAT_ID})[dept]||env.SUPPORT_CHAT_ID||null;
}
function operatorChats(env){return [env.SUPPORT_CHAT_ID,env.TECH_CHAT_ID,env.ACCOUNTING_CHAT_ID,env.SUBSCRIBER_CHAT_ID,env.CONNECTION_CHAT_ID].filter(Boolean).map(String)}
function isOperatorChat(env,id){return operatorChats(env).includes(String(id))}
function nameOf(u){return [u?.first_name,u?.last_name].filter(Boolean).join(' ')||(u?.username?`@${u.username}`:String(u?.telegram_id||'—'))}
function fmt(v,lang='uz'){try{return new Intl.DateTimeFormat(lang==='ru'?'ru-RU':'uz-UZ',{timeZone:'Asia/Tashkent',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return String(v||'—')}}

async function showHome(env,chatId,lang){
  const caption=L(lang,
    `⚡️ <b>${BOT_NAME}</b>\n\nMurojaat yuborish endi juda oson: bo‘limni tanlang va <b>bitta xabarda yozing</b>. Login, manzil yoki telefon majburiy emas.\n\n👇 Kerakli bo‘limni tanlang:`,
    `⚡️ <b>${BOT_NAME}</b>\n\nОтправить обращение теперь просто: выберите отдел и <b>напишите одним сообщением</b>. Логин, адрес и телефон не обязательны.\n\n👇 Выберите раздел:`);
  try{await sendChatAction(env,chatId,'upload_photo');await sendPhoto(env,chatId,MEDIA.homeBanner,caption,{reply_markup:homeKeyboard(lang)})}
  catch{await sendMessage(env,chatId,caption,{reply_markup:homeKeyboard(lang)})}
}
async function showDepartments(env,chatId,lang){return sendMessage(env,chatId,L(lang,'✍️ <b>Kimga yozamiz?</b>\n\nBo‘limni tanlang, keyin muammo yoki savolingizni yozing.','✍️ <b>Куда написать?</b>\n\nВыберите отдел, затем напишите проблему или вопрос.'),{reply_markup:departmentsKeyboard(lang)})}
async function startCompose(env,user,chatId,department,category='other'){
  const lang=user.language||'uz',d=departmentMeta(department,lang),c=categoryMeta(category,lang);
  await setSession(env,user.telegram_id,'compose',{department,category});
  return sendMessage(env,chatId,`${d.icon} <b>${escapeHtml(d.title)}</b>\n${c.icon} ${escapeHtml(c.title)}\n\n${L(lang,'✍️ Muammo yoki savolingizni hozir yozing. Qisqa matn ham bo‘ladi. Rasm/fayl ham yuborishingiz mumkin.','✍️ Напишите проблему или вопрос сейчас. Можно коротко. Также можно отправить фото/файл.')}\n\n${user.phone?`📞 ${escapeHtml(user.phone)}`:L(lang,'ℹ️ Telefon kiritish shart emas — operator shu bot orqali javob beradi.','ℹ️ Телефон не обязателен — оператор ответит через этот бот.')}`,{reply_markup:removeKeyboard});
}

async function showProfile(env,chatId,user){const lang=user.language||'uz';return sendMessage(env,chatId,[`👤 <b>${L(lang,'Profilim','Мой профиль')}</b>`,'',`🙍 ${escapeHtml(nameOf(user))}`,`🔐 ${escapeHtml(user.account_login||'—')}`,`📍 ${escapeHtml(user.address||'—')}`,`📞 ${escapeHtml(user.phone||'—')}`,'',L(lang,'Profil majburiy emas. To‘ldirsangiz operatorga qo‘shimcha ma’lumot boradi.','Профиль не обязателен. Если заполнить, оператор получит дополнительные данные.')].join('\n'),{reply_markup:inlineKeyboard([[{text:L(lang,'✏️ Profilni tahrirlash','✏️ Изменить профиль'),callback_data:'profile:edit'}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]])})}
async function startProfile(env,user,chatId){await setSession(env,user.telegram_id,'profile_account',{});return sendMessage(env,chatId,L(user.language||'uz','🔐 Login/shartnoma raqamini yuboring. Bilmasangiz <code>-</code>.','🔐 Отправьте логин/номер договора. Если не знаете — <code>-</code>.'))}

async function deliverTicket(env,no){
  const t=await getTicket(env,no); if(!t)return null;
  const u=await getUser(env,t.telegram_id),lang=u?.language||'uz',d=departmentMeta(t.department,lang),c=categoryMeta(t.category,lang);
  const preferred=mainSupport(env,t.department); if(!preferred)throw new Error('No support chat configured');
  const text=[`${t.priority==='critical'?'🚨':t.priority==='high'?'🔴':t.priority==='low'?'🟢':'🟡'} <b>${escapeHtml(t.priority.toUpperCase())} · ${escapeHtml(no)}</b>`,'━━━━━━━━━━━━━━',`${d.icon} <b>${escapeHtml(d.title)}</b>`,`${c.icon} ${escapeHtml(c.title)}`,`👤 ${escapeHtml(nameOf(u))} · <code>${t.telegram_id}</code>`,u?.username?`🔗 @${escapeHtml(u.username)}`:null,t.account_login?`🔐 <code>${escapeHtml(t.account_login)}</code>`:null,t.address?`📍 ${escapeHtml(t.address)}`:null,t.phone?`📞 ${escapeHtml(t.phone)}`:null,'',`📝 <b>${L(lang,'Murojaat','Обращение')}:</b>`,escapeHtml(t.description),'','💬 Reply qiling — javob mijozga bot orqali boradi.'].filter(Boolean).join('\n');
  const candidates=[preferred]; if(env.SUPPORT_CHAT_ID&&String(env.SUPPORT_CHAT_ID)!==String(preferred))candidates.push(env.SUPPORT_CHAT_ID);
  let lastErr=null;
  for(const chatId of candidates){try{const m=await sendMessage(env,chatId,text,{reply_markup:operatorKeyboard(no)});await setSupportMessage(env,no,chatId,m.message_id);await deliveryDone(env,no);return{chatId,messageId:m.message_id}}catch(e){lastErr=e}}
  throw lastErr||new Error('Delivery failed');
}
async function safeDeliver(env,no,msg=null){
  try{const x=await deliverTicket(env,no);if(x&&msg&&!msg.text&&(msg.photo||msg.document||msg.video||msg.voice||msg.audio)){try{await copyMessage(env,x.chatId,msg.chat.id,msg.message_id)}catch{}}return true}
  catch(e){await enqueueDelivery(env,no,e);console.error('ticket delivery queued',{no,error:String(e)});return false}
}
async function createFromMessage(env,user,data,msg,forcedText=null){
  const lang=user.language||'uz'; const body=String(forcedText??msg?.text??msg?.caption??'').trim(); const media=Boolean(msg?.photo||msg?.document||msg?.video||msg?.voice||msg?.audio);
  if(!body&&!media)return null;
  const description=(body||L(lang,'Rasm/fayl yuborildi','Отправлено фото/файл')).slice(0,2000);
  const no=await createTicket(env,{telegramId:user.telegram_id,department:data.department||'tech',category:data.category||'other',description,accountLogin:user.account_login,address:user.address,phone:user.phone,priority:priorityFor(data.category,description),telegramMessageId:msg?.message_id||null});
  await clearSession(env,user.telegram_id);
  await safeDeliver(env,no,msg);
  return no;
}
async function ticketSuccess(env,chatId,lang,no){return sendMessage(env,chatId,L(lang,`✅ <b>Murojaat yuborildi</b>\n\n🎫 <code>${no}</code>\n\nOperator javobi shu botga keladi.`,`✅ <b>Обращение отправлено</b>\n\n🎫 <code>${no}</code>\n\nОтвет оператора придёт в этот бот.`),{reply_markup:inlineKeyboard([[{text:L(lang,'📂 Murojaatni ko‘rish','📂 Открыть обращение'),callback_data:`ticket:view:${no}`}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]])})}

async function showTariffMenu(env,chatId,lang){return sendMessage(env,chatId,L(lang,'📶 <b>Tariflar</b>\n\nSeriyani tanlang:','📶 <b>Тарифы</b>\n\nВыберите серию:'),{reply_markup:inlineKeyboard([[{text:'⚡ TEZKOR',callback_data:'tariff:tezkor:0'},{text:'🌐 OnLine',callback_data:'tariff:online:0'}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]])})}
async function showTariffs(env,chatId,lang,series,page=0){const items=await getTariffs(env,series),pp=4,pages=Math.max(1,Math.ceil(items.length/pp));page=Math.max(0,Math.min(Number(page)||0,pages-1));const body=items.slice(page*pp,page*pp+pp).map(x=>`⚡ <b>${escapeHtml(x.name)}</b>\n💳 ${Number(x.price||0).toLocaleString('ru-RU')} ${L(lang,'so‘m/oy','сум/мес')}\n🌙 ${escapeHtml(x.evening||'—')} Mbit/s\n☀️ ${escapeHtml(x.daytime||'—')} Mbit/s`).join('\n\n');const nav=[];if(page>0)nav.push({text:'⬅️',callback_data:`tariff:${series}:${page-1}`});nav.push({text:`${page+1}/${pages}`,callback_data:'noop'});if(page<pages-1)nav.push({text:'➡️',callback_data:`tariff:${series}:${page+1}`});return sendMessage(env,chatId,`📶 <b>${series==='tezkor'?'TEZKOR':'OnLine'}</b>\n\n${body||'—'}`,{reply_markup:inlineKeyboard([nav,[{text:L(lang,'✍️ Tarif bo‘yicha yozish','✍️ Написать по тарифу'),callback_data:'quick:subscriber:tariff_change'}],[{text:L(lang,'⬅️ Tariflar','⬅️ Тарифы'),callback_data:'home:tariffs'}]])})}
async function showServices(env,chatId,lang){const ru={'Wi‑Fi sozlash':'Настройка Wi‑Fi','Kompyuterda tarmoqni sozlash':'Настройка сети на компьютере','LAN sozlash':'Настройка LAN','Tarmoq uskunasi diagnostikasi':'Диагностика сетевого оборудования','IPTV sozlash':'Настройка IPTV','TV/pristavka sozlash':'Настройка ТВ/приставки','Router yetkazib berish':'Доставка роутера','Ustani chaqirish':'Вызов мастера'};const lines=POPULAR_SERVICES.map(([n,p])=>`• ${escapeHtml(lang==='ru'?(ru[n]||n):n)} — <b>${escapeHtml(p)}</b>`).join('\n');return sendMessage(env,chatId,`${L(lang,'🧰 <b>Xizmatlar</b>','🧰 <b>Услуги</b>')}\n\n${lines}`,{reply_markup:inlineKeyboard([[{text:L(lang,'✍️ Xizmat bo‘yicha yozish','✍️ Написать по услуге'),callback_data:'quick:subscriber:other'}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]])})}
async function showPromo(env,chatId,lang){const cap=L(lang,'🎁 <b>FiberNet aksiyalari</b>\n\nSavol bo‘lsa shu botda yozing.','🎁 <b>Акции FiberNet</b>\n\nЕсли есть вопрос — напишите прямо здесь.');const kb=inlineKeyboard([[{text:L(lang,'✍️ Aksiya bo‘yicha yozish','✍️ Написать по акции'),callback_data:'quick:subscriber:other'}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]]);try{return await sendPhoto(env,chatId,lang==='ru'?MEDIA.promoRu:MEDIA.promoUz,cap,{reply_markup:kb})}catch{return sendMessage(env,chatId,cap,{reply_markup:kb})}}
async function showContacts(env,chatId,lang){return sendMessage(env,chatId,[`☎️ <b>${L(lang,'FiberNet aloqa','Контакты FiberNet')}</b>`,'',`📞 <b>${CONTACTS.phone}</b>`,`🧑‍💻 ${CONTACTS.supportEmail}`,`📧 ${CONTACTS.infoEmail}`,`📍 ${escapeHtml(lang==='ru'?CONTACTS.addressRu:CONTACTS.addressUz)}`].join('\n'),{reply_markup:inlineKeyboard([[{text:L(lang,'✍️ Murojaat yozish','✍️ Написать обращение'),callback_data:'home:departments'}],[{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]])})}

async function showTickets(env,chatId,user){const lang=user.language||'uz',rows=await listUserTickets(env,user.telegram_id,12);if(!rows.length)return sendMessage(env,chatId,L(lang,'📭 Hali murojaat yo‘q.','📭 Обращений пока нет.'),{reply_markup:homeKeyboard(lang)});const b=rows.map(x=>[{text:`${x.status==='closed'?'✅':x.stage==='waiting_customer'?'⏳':'🟡'} ${x.ticket_no}`,callback_data:`ticket:view:${x.ticket_no}`}]);b.push([{text:L(lang,'🏠 Bosh menyu','🏠 Главное меню'),callback_data:'home:main'}]);return sendMessage(env,chatId,L(lang,'📂 <b>Murojaatlarim</b>','📂 <b>Мои обращения</b>'),{reply_markup:inlineKeyboard(b)})}
async function showTicket(env,chatId,user,no){const t=await getTicket(env,no);if(!t||String(t.telegram_id)!==String(user.telegram_id))return;const lang=user.language||'uz',d=departmentMeta(t.department,lang),c=categoryMeta(t.category,lang),b=[];if(t.status==='open')b.push([{text:L(lang,'💬 Javob yozish','💬 Ответить'),callback_data:`ticket:reply:${no}`}]);b.push([{text:L(lang,'⬅️ Murojaatlar','⬅️ Обращения'),callback_data:'home:tickets'}]);return sendMessage(env,chatId,[`🎫 <b>${escapeHtml(no)}</b>`,`${t.status==='closed'?'✅':'🟡'} ${escapeHtml(t.stage)}`,`${d.icon} ${escapeHtml(d.title)}`,`${c.icon} ${escapeHtml(c.title)}`,t.assigned_name?`👨‍💻 ${escapeHtml(t.assigned_name)}`:null,`🕒 ${escapeHtml(fmt(t.created_at,lang))}`,'',`📝 ${escapeHtml(t.description)}`].filter(Boolean).join('\n'),{reply_markup:inlineKeyboard(b)})}

async function handleSession(env,msg,user,s){if(!s)return false;const lang=user.language||'uz',d=sessionData(s);
  if(s.state==='compose'){const no=await createFromMessage(env,user,d,msg);if(!no){await sendMessage(env,msg.chat.id,L(lang,'✍️ Matn, rasm yoki fayl yuboring.','✍️ Отправьте текст, фото или файл.'));return true}await ticketSuccess(env,msg.chat.id,lang,no);return true}
  if(s.state==='profile_account'){if(!msg.text)return true;d.accountLogin=msg.text.trim()==='-'?null:msg.text.trim().slice(0,80);await setSession(env,user.telegram_id,'profile_address',d);await sendMessage(env,msg.chat.id,L(lang,'📍 Manzilingizni yozing:','📍 Укажите адрес:'));return true}
  if(s.state==='profile_address'){if(!msg.text?.trim())return true;d.address=msg.text.trim().slice(0,300);await setSession(env,user.telegram_id,'profile_phone',d);await sendMessage(env,msg.chat.id,L(lang,'📞 Telefonni yuboring yoki kontakt tugmasini bosing:','📞 Отправьте телефон или нажмите кнопку контакта:'),{reply_markup:contactKeyboard(L(lang,'📱 O‘z raqamim','📱 Мой номер'))});return true}
  if(s.state==='profile_phone'){const p=normalizePhone(msg.contact?.phone_number||msg.text||'');if(!p){await sendMessage(env,msg.chat.id,L(lang,'⚠️ Raqamni qayta yuboring.','⚠️ Отправьте номер ещё раз.'));return true}d.phone=p;await saveProfile(env,user.telegram_id,d);await clearSession(env,user.telegram_id);await sendMessage(env,msg.chat.id,L(lang,'✅ Profil saqlandi.','✅ Профиль сохранён.'),{reply_markup:removeKeyboard});await showHome(env,msg.chat.id,lang);return true}
  if(s.state==='ticket_reply'){const t=await getTicket(env,d.ticketNo);if(!t||String(t.telegram_id)!==String(user.telegram_id)||t.status!=='open'){await clearSession(env,user.telegram_id);return true}const body=String(msg.text||msg.caption||'').trim(),chat=t.support_chat_id||mainSupport(env,t.department);try{if(body)await sendMessage(env,chat,`💬 <b>${escapeHtml(t.ticket_no)} · mijoz</b>\n\n${escapeHtml(body)}`,t.support_message_id?{reply_to_message_id:t.support_message_id}:{});if(!msg.text&&(msg.photo||msg.document||msg.video||msg.voice||msg.audio))await copyMessage(env,chat,msg.chat.id,msg.message_id);await addMessage(env,t.ticket_no,'user',user.telegram_id,body||'[attachment]',msg.message_id);await setStage(env,t.ticket_no,'in_progress');await clearSession(env,user.telegram_id);await sendMessage(env,msg.chat.id,L(lang,'✅ Javob operatorga yuborildi.','✅ Ответ отправлен оператору.'),{reply_markup:homeKeyboard(lang)})}catch(e){await sendMessage(env,msg.chat.id,L(lang,'⚠️ Hozir yuborishda xato bo‘ldi. Xabaringiz saqlanmagan, yana urinib ko‘ring.','⚠️ Ошибка отправки. Сообщение не сохранено, попробуйте ещё раз.'))}return true}
  return false}

async function privateMessage(env,msg){let user=await upsertUser(env,msg.from);const text=String(msg.text||'').trim(),lang=user.language||'uz';if(text==='/start'){await clearSession(env,user.telegram_id);if(!user.language)return sendMessage(env,msg.chat.id,'🌐 <b>Tilni tanlang / Выберите язык</b>',{reply_markup:languageKeyboard()});return showHome(env,msg.chat.id,user.language)}if(text==='/cancel'){await clearSession(env,user.telegram_id);await sendMessage(env,msg.chat.id,L(lang,'❎ Bekor qilindi.','❎ Отменено.'),{reply_markup:removeKeyboard});return showHome(env,msg.chat.id,lang)}if(text==='/profile')return showProfile(env,msg.chat.id,user);if(text==='/tickets')return showTickets(env,msg.chat.id,user);if(text==='/language')return sendMessage(env,msg.chat.id,'🌐 <b>Til / Язык</b>',{reply_markup:languageKeyboard()});const s=await getSession(env,user.telegram_id);if(await handleSession(env,msg,user,s))return;if(!user.language)return sendMessage(env,msg.chat.id,'🌐 <b>Tilni tanlang / Выберите язык</b>',{reply_markup:languageKeyboard()});if(!text)return showHome(env,msg.chat.id,lang);const i=classifyText(text);if(i.action==='home')return showHome(env,msg.chat.id,lang);if(i.action==='tariffs')return showTariffMenu(env,msg.chat.id,lang);if(i.action==='departments')return showDepartments(env,msg.chat.id,lang);const no=await createFromMessage(env,user,{department:i.department,category:i.category},msg,text);if(no)return ticketSuccess(env,msg.chat.id,lang,no)}

async function operatorMessage(env,msg){const text=String(msg.text||'').trim();let t=null;if(msg.reply_to_message?.message_id)t=await getTicketBySupportMessage(env,msg.chat.id,msg.reply_to_message.message_id);if(t&&t.status==='open'&&!text.startsWith('/')){const u=await getUser(env,t.telegram_id),lang=u?.language||'uz',body=String(msg.text||msg.caption||'').trim();if(body)await sendMessage(env,t.telegram_id,`👨‍💻 <b>FiberNet ${L(lang,'operatori','оператор')}</b>\n\n${escapeHtml(body)}`,{reply_markup:inlineKeyboard([[{text:L(lang,'💬 Javob yozish','💬 Ответить'),callback_data:`ticket:reply:${t.ticket_no}`} ]])});else if(msg.photo||msg.document||msg.video||msg.voice||msg.audio){try{await copyMessage(env,t.telegram_id,msg.chat.id,msg.message_id)}catch{}}await addMessage(env,t.ticket_no,'operator',msg.from.id,body||'[attachment]',msg.message_id);await assignTicket(env,t.ticket_no,{id:msg.from.id,name:operatorName(msg.from)});await setStage(env,t.ticket_no,'in_progress',{id:msg.from.id,name:operatorName(msg.from)});return}if(text==='/queue'||text==='/tickets'){const r=await listQueue(env,30),body=r.length?r.map(x=>`${x.priority==='critical'?'🚨':x.priority==='high'?'🔴':'🟡'} <b>${escapeHtml(x.ticket_no)}</b> · ${escapeHtml(x.department)} · ${escapeHtml(x.stage)}\n${escapeHtml((x.description||'').slice(0,120))}`).join('\n\n'):'✅ Ochiq murojaat yo‘q.';return sendMessage(env,msg.chat.id,`📥 <b>FiberNet Queue</b>\n\n${body}`)}if(text==='/stats'){const s=await stats(env);return sendMessage(env,msg.chat.id,`📊 <b>FiberNet v5</b>\n\n📚 ${s.total||0}\n🟡 ${s.open_count||0}\n✅ ${s.closed_count||0}`)}}

async function callback(env,q){try{await answerCallback(env,q.id)}catch{}let user=await upsertUser(env,q.from);const lang=user.language||'uz',data=q.data||'',chatId=q.message.chat.id;if(data==='noop')return;
  if(isOperatorChat(env,chatId)&&data.startsWith('op:')){const[,a,no]=data.split(':'),t=await getTicket(env,no);if(!t||t.status!=='open')return;const op={id:q.from.id,name:operatorName(q.from)};if(a==='claim'){await assignTicket(env,no,op);return sendMessage(env,chatId,`👨‍💻 ${escapeHtml(op.name)} · ${escapeHtml(no)}`)}if(a==='wait'){await assignTicket(env,no,op);await setStage(env,no,'waiting_customer',op);const u=await getUser(env,t.telegram_id);return sendMessage(env,t.telegram_id,L(u?.language||'uz',`⏳ Operator <code>${no}</code> bo‘yicha javobingizni kutmoqda.`,`⏳ Оператор ждёт ваш ответ по <code>${no}</code>.`),{reply_markup:inlineKeyboard([[{text:L(u?.language||'uz','💬 Javob yozish','💬 Ответить'),callback_data:`ticket:reply:${no}`} ]])})}if(a==='resolve'){await assignTicket(env,no,op);await setStage(env,no,'resolved',op);const u=await getUser(env,t.telegram_id);return sendMessage(env,t.telegram_id,L(u?.language||'uz',`✅ Muammo hal qilindi deb belgilandi: <code>${no}</code>`,`✅ Обращение отмечено решённым: <code>${no}</code>`),{reply_markup:inlineKeyboard([[{text:'👍',callback_data:`feedback:${no}:1`},{text:'👎',callback_data:`feedback:${no}:0`}],[{text:L(u?.language||'uz','💬 Muammo davom etyapti','💬 Проблема осталась'),callback_data:`ticket:reply:${no}`} ]])})}if(a==='close'){if(await closeTicket(env,no)){const u=await getUser(env,t.telegram_id);await sendMessage(env,t.telegram_id,L(u?.language||'uz',`✅ Murojaat yopildi: <code>${no}</code>`,`✅ Обращение закрыто: <code>${no}</code>`),{reply_markup:homeKeyboard(u?.language||'uz')});try{await editReplyMarkup(env,chatId,q.message.message_id)}catch{}}return}}
  if(data.startsWith('lang:')){const n=data==='lang:ru'?'ru':'uz';await setLanguage(env,user.telegram_id,n);await clearSession(env,user.telegram_id);return showHome(env,chatId,n)}
  if(data==='home:main'){await clearSession(env,user.telegram_id);return showHome(env,chatId,lang)}if(data==='home:language')return sendMessage(env,chatId,'🌐 <b>Til / Язык</b>',{reply_markup:languageKeyboard()});if(data==='home:tech')return sendMessage(env,chatId,L(lang,'🛠 <b>Texnik yordam</b>\n\nMuammo turini tanlang yoki darhol yozing:','🛠 <b>Техподдержка</b>\n\nВыберите тему или напишите сразу:'),{reply_markup:techKeyboard(lang)});if(data==='home:accounting')return sendMessage(env,chatId,L(lang,'💳 <b>Buxgalteriya</b>\n\nMavzuni tanlang yoki darhol yozing:','💳 <b>Бухгалтерия</b>\n\nВыберите тему или напишите сразу:'),{reply_markup:accountingKeyboard(lang)});if(data==='home:subscriber')return sendMessage(env,chatId,L(lang,'👥 <b>Abonent bo‘limi</b>\n\nMavzuni tanlang yoki darhol yozing:','👥 <b>Абонентский отдел</b>\n\nВыберите тему или напишите сразу:'),{reply_markup:subscriberKeyboard(lang)});if(data==='home:departments')return showDepartments(env,chatId,lang);if(data==='home:profile')return showProfile(env,chatId,user);if(data==='home:tickets')return showTickets(env,chatId,user);if(data==='home:tariffs')return showTariffMenu(env,chatId,lang);if(data==='home:services')return showServices(env,chatId,lang);if(data==='home:promo')return showPromo(env,chatId,lang);if(data==='home:contacts')return showContacts(env,chatId,lang);if(data==='profile:edit')return startProfile(env,user,chatId);
  if(data.startsWith('quick:')){const[,dept,cat='other']=data.split(':');return startCompose(env,user,chatId,dept,cat)}
  if(data.startsWith('tariff:')){const[,s,p]=data.split(':');return showTariffs(env,chatId,lang,s,Number(p))}
  if(data.startsWith('ticket:view:'))return showTicket(env,chatId,user,data.slice('ticket:view:'.length));
  if(data.startsWith('ticket:reply:')){const no=data.slice('ticket:reply:'.length),t=await getTicket(env,no);if(!t||String(t.telegram_id)!==String(user.telegram_id)||t.status!=='open')return;await setSession(env,user.telegram_id,'ticket_reply',{ticketNo:no});return sendMessage(env,chatId,L(lang,'💬 Javobingizni yozing yoki media yuboring:','💬 Напишите ответ или отправьте медиа:'))}
  if(data.startsWith('feedback:')){const[,no,r]=data.split(':'),t=await getTicket(env,no);if(!t||String(t.telegram_id)!==String(user.telegram_id))return;await setRating(env,no,user.telegram_id,Number(r));return sendMessage(env,chatId,L(lang,'💙 Rahmat!','💙 Спасибо!'),{reply_markup:homeKeyboard(lang)})}
}

async function retryDeliveries(env){const rows=await pendingDeliveries(env,20);for(const x of rows){try{await deliverTicket(env,x.ticket_no);await deliveryDone(env,x.ticket_no)}catch(e){await deliveryFailed(env,x.ticket_no,e)}}}
async function processUpdate(env,u){if(!await claimUpdate(env,u.update_id))return;try{if(u.callback_query)await callback(env,u.callback_query);else if(u.message){if(u.message.chat?.type==='private')await privateMessage(env,u.message);else if(isOperatorChat(env,u.message.chat?.id))await operatorMessage(env,u.message)}}catch(e){await releaseUpdate(env,u.update_id);throw e}}
async function webhook(req,env){if(!env.TELEGRAM_WEBHOOK_SECRET||req.headers.get('X-Telegram-Bot-Api-Secret-Token')!==env.TELEGRAM_WEBHOOK_SECRET)return new Response('Unauthorized',{status:401});let u;try{u=await req.json()}catch{return new Response('Bad Request',{status:400})}if(!Number.isInteger(u.update_id))return new Response('ok');await ensureV5Schema(env);await processUpdate(env,u);return new Response('ok')}

export default {
  async fetch(req,env){const url=new URL(req.url);if(req.method==='POST'&&url.pathname==='/telegram/webhook'){try{return await webhook(req,env)}catch(e){console.error('FiberNet v5 webhook error',{error:String(e),stack:e?.stack});return new Response('Retry',{status:500})}}if(req.method==='GET'&&url.pathname==='/health'){try{await ensureV5Schema(env);return Response.json({ok:true,service:'fibernet-bot',version:VERSION,mode:'direct-write',stats:await stats(env)})}catch(e){return Response.json({ok:false,version:VERSION,error:String(e)},{status:503})}}if(url.pathname==='/')return new Response(`FiberNet Assistant v${VERSION} is running.`);return new Response('Not found',{status:404})},
  async scheduled(controller,env,ctx){ctx.waitUntil((async()=>{try{await ensureV5Schema(env);await cleanupUpdates(env);await retryDeliveries(env)}catch(e){console.error('v5 maintenance',String(e))}if(controller?.cron==='15 23 * * *'){try{await syncOfficialSources(env)}catch(e){console.error('v5 sync',String(e))}}})())}
};
export const __test={normalizePhone,classifyText,priorityFor};
